name: Laravel CI with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.5.3
        with:
          fetch-depth: 0  # importante para SonarCloud

      - name: Setup PHP
        uses: shivammathur/setup-php@8f30b889bf0cc6e6a6e03a10e1e5cfc8dc5cbb5e # v2.30.4
        with:
          php-version: '8.2'   # ajusta si usas otra versiÃ³n
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests with coverage
        run: php artisan test --coverage-clover=coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ab92f4e4152ee255c5036e52a6a3372fa51179dd # master commit
        with:
          args: >
            -Dsonar.projectKey=Dieggo19_CRUD_BASICO
            -Dsonar.organization=dieggo19
            -Dsonar.sources=app
            -Dsonar.tests=tests
            -Dsonar.php.coverage.reportPaths=coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
